name: Run Python Scripts

on:
  push:
    branches:
      - main  # Replace with your branch name if different
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright openpyxl
        playwright install
        pip install pandas playwright playwright-stealth
        playwright install-deps

    - name: Run p2.py
      run: python p2.py

    - name: Run p4.py
      run: python p4.py

    - name: Run p5.py
      run: python p5.py

    - name: Run p6.py
      run: python p6.py

    - name: Upload all Excel files
      uses: actions/upload-artifact@v4  # ✅ Fixed deprecated action
      with:
        name: stock_data_files
        path: "*.xlsx"

    - name: Workflow Completed Successfully
      run: echo "All scripts ran successfully!"
