name: Run Python Scripts

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright openpyxl
        playwright install

    - name: Run Python Scripts
      run: |
        python p2.py
        python p4.py
        python p5.py
        python p6.py

    - name: Upload Generated Excel Files
      uses: actions/upload-artifact@v3
      with:
        name: stock_data_files
        path: |
          f1.xlsx
          f2.xlsx
          kotak_stock_data.xlsx
          kotak_stock_long.xlsx
