name: Run Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas playwright playwright-stealth
          playwright install
          playwright install-deps

      - name: Run p4.py
        run: |
          python p4.py || echo "p4.py failed, continuing..."

      - name: Run p5.py
        run: |
          python p5.py || echo "p5.py failed, continuing..."

      - name: Upload Debug Screenshot (if failed)
        if: failure()
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: debug-screenshot
          path: debug.png

      - name: Commit & Push Updated Excel Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add kotak_stock_data.xlsx
          git commit -m "Updated stock data" || echo "No changes to commit"
          git push
